src/lib.rs
src/types/mod.rs
src/types/multipoint.rs

Add MultiPoint support

---

src/lib.rs
src/types/geometrycollection.rs
src/types/linestring.rs
src/types/mod.rs
src/types/multilinestring.rs
src/types/multipoint.rs
src/types/multipolygon.rs
src/types/point.rs
src/types/polygon.rs

Implement Geometry Collection

---

src/lib.rs
src/types/coord.rs
src/types/geometrycollection.rs
src/types/linestring.rs
src/types/mod.rs
src/types/multilinestring.rs
src/types/multipoint.rs
src/types/multipolygon.rs
src/types/point.rs
src/types/polygon.rs

Allow Wkt items to be EMPTY

---

Cargo.toml
src/lib.rs
src/towkt.rs

Fixes #20
This is pretty messy and there is definitely room to make this cleaner
in the future. Might be helpful to make geo more ergonomic.

Add ToWkt trait, implement it for geo::Geometry

---

Cargo.toml
src/lib.rs

These should be public, not private.

Make `Wkt` methods public.

---

src/conversion.rs
src/lib.rs
src/towkt.rs
src/types/mod.rs

For conversions that fail I use a custom function `try_into_geometry` instead of custom `TryInto` trait to not generate conflicts when `TryInto` will be stable

Convert wkt types to geo types

---

Cargo.toml
src/towkt.rs

Update geo types 2

---

src/tokenizer.rs

Was running AFL on this library and found that large but bad inputs could cause stack overflows.  Switched the Tokenizer's `read_until_whitespace` and `next` to use a non-recursive implementation.  
This has the side effect of improving performance.  On my Ubuntu VM, `cargo bench` runtime reduced by 18% on parse small and 60% on parse big.

Remove recursion to prevent stack overflow

---

Cargo.toml
src/towkt.rs

Hello,
I'm trying to cleanup dependencies in my project, and have a `geo-types 0.6` baseline.
I hope the new matches have been coded in the same spirit as the rest.

Update dependencies (geo-types 0.6)

---

CHANGES.md
Cargo.toml
src/conversion.rs
src/lib.rs
src/tokenizer.rs
src/towkt.rs
src/types/coord.rs
src/types/geometrycollection.rs
src/types/linestring.rs
src/types/multilinestring.rs
src/types/multipoint.rs
src/types/multipolygon.rs
src/types/point.rs
src/types/polygon.rs

Mkirk/geo types 0.7

---

CHANGES.md
Cargo.toml
src/tokenizer.rs

Approximately 40% faster, not all numeric chars are digits

---

CHANGES.md
Cargo.toml

0.9.2 release

---

Cargo.toml

Remove authors manifest field

---

CHANGES.md
Cargo.toml

prepare for 0.10.1 release

---

CHANGES.md
Cargo.toml
src/deserialize/geo_types.rs
src/deserialize/mod.rs
src/geo_types_from_wkt.rs
src/lib.rs
src/tokenizer.rs
src/types/coord.rs
src/types/geometrycollection.rs
src/types/linestring.rs
src/types/multilinestring.rs
src/types/multipoint.rs
src/types/multipolygon.rs
src/types/point.rs
src/types/polygon.rs

---
Fixes https://github.com/georust/wkt/issues/102
~~This is based on #101, which @rmanoka already approved (thanks!), but I'm going to wait just a bit longer to merge it in case someone else wanted to take a look at it.~~
**update:** #101 has been merged, and this is ready for review!

TryFromWkt for integer geometries

---

src/geo_types_from_wkt.rs
src/tokenizer.rs
src/types/geometrycollection.rs

Fix some clippy warnings

---

CHANGES.md
src/infer_type.rs
src/lib.rs
src/types/dimension.rs
src/types/geometry_type.rs
src/types/mod.rs

Infer geometry type and dimension from WKT

---

CHANGES.md
Cargo.toml

prepare for v0.11.1 release

---

src/to_wkt/mod.rs

---
Note that this is a PR to your branch @kylebarron

Retain io::error details

---

CHANGES.md
src/types/coord.rs

Add `Copy` impl to `Coord`

---

src/types/geometrycollection.rs
src/types/linestring.rs
src/types/multilinestring.rs
src/types/multipoint.rs
src/types/multipolygon.rs
src/types/polygon.rs

---
Ref https://github.com/georust/wkt/pull/135#discussion_r2045514056

Return `Option<Self>` in fallible constructors

---

src/wkt_macro.rs

---
PR into #142 to avoid pushing to that branch directly

(editing #142) DRY up WKT macros
