- src/types/coord.rs
- src/types/linestring.rs
- src/types/mod.rs
- src/types/multipoint.rs
- src/types/point.rs
- src/types/polygon.rs
So I went a little nuts here, but it makes some of the from_tokens
implementations really concise and sexy.
> Reduce repetitive 'comma' implementations

- Cargo.toml
- README.md
I'm the only contributor, so this should be a straightforward license
change.
> Relicense as "MIT/Apache-2.0".

- src/lib.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
fix https://github.com/georust/rust-wkt/issues/31
write some wkt
- POINT EMPTY
- POINT(..)
- POINT Z(..)
- POINT ZM(..)
- LINESTRING EMPTY
- LINESTRING(...)
- POLYGON EMPTY
- POLYGON (...)
- MULTIPOINT EMPTY
- MULTIPOINT (...)
- MULTILINESTRING EMPTY
- MULTILINESTRING (...)
- MULTIPOLYGON EMPTY
- MULTIPOLYGON (...)
- GEOMETRYCOLLECTION EMPTY
- GEOMETRYCOLLECTION (...)
I have not handled every case like `MULTILINESTRING ZM` but we can make an issue for that.
I don't know the exhaustive list of cases
> Implement Display for geometries

- src/lib.rs
- src/tokenizer.rs
In Wkt::from_str, invalid numbers are causing a panic but other kinds of input return an Err.
> Don't panic on invalid number

- Cargo.toml
- src/towkt.rs
update to geo_types 0.4
It might be worth waiting if a new version is pushed after [this merge](https://github.com/georust/geo/pull/347), but anyway I think it'll be a patch version change.
> upgrade geo_types

- Cargo.toml
- src/conversion.rs
- src/lib.rs
- src/tokenizer.rs
- src/towkt.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
Attempt to close #33. I based this off of the conversion implementation in [geojson](https://github.com/georust/geojson/blob/master/src/conversion.rs) and only used generic types for converting to `geo_types` objects
Initially I tried to update the `From` trait implementation, but I used `Into` instead because updating `From` gave me the following error:
```
type parameter `T` must be used as the type parameter for some local type
```
If I missed something that would make `From` work instead I can make that change. Let me know if I should change that or anything else here, thanks!
> Use generic type for precision in conversion

- Cargo.toml
Hello, I encountered this bug and I fixed by updating `geo_types`. I tested the patch with `cargo test` and it works.
```   |
107 |           let multi_polygon = match wkt::conversion::try_into_geometry(&wkt_shape)                                            
|  ___________________________________-
108 | |             .expect("Failed to convert polygon wkt to geo_types")                                                           
| |_________________________________________________________________- this expression has type `geo_types::geometry::Geometry<f64>`
109 |           {
110 |               Geometry::MultiPolygon(multi_polygon) => multi_polygon,                                                         
|               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum …
```
> update to the last geo_types version

- src/conversion.rs
- src/lib.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
This is a couple separate but related things...
The main new functionality is that you can call `Geometry::from(wkt)`
Along the way, I replaced the `Try/Into` impls with `Try/From`. We should prefer TryFrom where possible since it is sometimes nicer to use and also gives you the TryInto impl for free.
Correspondingly, I deprecated methods like `try_into_geometry` in favor of `geometry.try_into` which I think is more discoverable.
One thing I was curious about - I think conventionally conversions are done via move, so the caller is responsible for any cloning, but previously all our conversions were done via references and our impls were creating new points for everything. That seemed a little strange to me, so I implemented all the new ones with the move semantics that I'm used to. I did …
> Try/From<Wkt> traits for Geometry

- CHANGES.md
- Cargo.toml
- src/conversion.rs
- src/lib.rs
---
**DRAFT**: depends on https://github.com/georust/geo/pull/614 being released first.
Add TryFrom for converting directly to `geo_types::Geometry` enum members. 
```
let ls: geo_types::LineString = geo_types::LineString::try_from(wkt).unwrap();
```
Previously it was:
```
let geom: geo_types::Geometry = geo_types::Geometry::from(wkt).unwrap();
let ls: geo_types::LineString = geo_types::LineString::try_from(geom).unwrap();
```
This introduced two new error cases, so I've also introduced `thiserror` which solves #49
FIXES https://github.com/georust/wkt/issues/49
> specific errors and `try_into` for inner geo-types

- CHANGES.md
- Cargo.toml
- src/deserialize.rs
- src/lib.rs
> impl serde::Deserialize for Wkt and Geometry (and helper function)

- README.md
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
Added a docs/crates badge.
🔥hot take🔥:  I removed the ci badge all together.
we no longer use travis ci. I could have changed this to use a GH actions
badge, but people can already see the build status next to the commit on
the front page. I don't think it warrants a redundant badge.
> add docs/crates badge. remove deprecated CI badge

- src/deserialize.rs
- src/lib.rs
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
-  > Add helper function for deserializing from WKT format into geo_types::Geometry
I think the existing unreleased note pretty much covers it 
---
Addresses one little bit of https://github.com/georust/wkt/issues/61, though leaves unanswered the bigger questions, around how to handle `GEOMETRYCOLLETION(POINT EMPTY)` etc.
This might be controversial as it arguably muddies the water for addressing #61 more comprehensively. Please take a look at #61 for context.
> deserialize point

- CHANGES.md
- benches/parse.rs
- src/conversion.rs
- src/deserialize.rs
> Support 'POINT EMPTY' conversion to geo_types

- CHANGES.md
- src/lib.rs
Refer discussion in #50 
+ support LINEARRING by parsing it as a LINESTRING
+ test LINEARRING parsing
---
> Minimal support for JTS extensions

- CHANGES.md
- src/lib.rs
- src/types/multipoint.rs
Postgis' `ST_AsText` function will serialize multipoints like
`MULTIPOINT(0 1, 2 3)`,
which would fail to deserialize because we expect a string like
`MULTIPOINT((0 1), (2 3))`.
In fact, the Postgis `ST_GeomFromText` function even accepts mixed
bracketing, like
`MULTIPOINT((0 1), 2 3)`.
This PR updates the parsing of multipoints to allow all these styles.
---
> Relax the parens requirement for multipoint

- CHANGES.md
- benches/parse.rs
- src/conversion.rs
- src/deserialize.rs
- src/lib.rs
- src/towkt.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
> Store a single geometry inside Wkt

- .github/workflows/test.yml
- CHANGES.md
- Cargo.toml
- src/conversion.rs
- src/deserialize.rs
- src/lib.rs
- src/tokenizer.rs
- src/towkt.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
> Migrate to 2021 edition and add examples

- .github/workflows/test.yml
- .gitignore
- CODE_OF_CONDUCT.md
- src/conversion.rs
- src/deserialize.rs
- src/lib.rs
- src/tokenizer.rs
- src/towkt.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
* Made a few changes similar to recent cleanup efforts with the geo repo
* spellchecking
* make clippy happier (there are still a few outstanding ones, todo in a separate PR)
* automatically run CI on PRs, not just push
- ~~[ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.~~
---
> Cargo fmt & clippy, run CI on PR, spelling

- src/conversion.rs
Use `coord!` macro instead of `geo_types::Coordinate<T> { x, y }`. Doing this makes coordinate creation consistent, and allows more flexibility in the geo_types repo to introduce object changes.
---
> Use geo_types macros to future proof

- CHANGES.md
- src/lib.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
Most of the user's code will stay the same, but will require `use std::str::FromStr;`
See also discussion in #77 
---
> BREAKING: move `Wkt::from_str` to `FromStr` trait

- .github/workflows/test.yml
- benches/parse.rs
In order to auto-catch bugs and code quality,
adding clippy and fmt to CI (same as geo)
- ~[ ] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.~
---
> Fix bench build bug, added CI lints

- CHANGES.md
- src/lib.rs
---
to address #83 and make it easier to go from Wkt to string representation. Includes test
> impl Display for Wkt

- Cargo.toml
- src/conversion.rs
- src/towkt.rs
This PR will make it easier to migrate to TZM (3D/M)
---
> Migrate to geo-type 0.7.4

- CHANGES.md
- src/towkt.rs
---
Fixes #55 - adds an easier API to serialize a geo-type.
~~Depends on #86, so merge that first.~~ Merged!
~~partially conflicts with #88, because I'm relying on the `ToWkt` trait.~~ superseded!
> Easier serialization of wkt with ToWkt::wkt_string/write_wkt

- CHANGES.md
- benches/parse.rs
- src/from_wkt.rs
- src/geo_types_from_wkt.rs
- src/lib.rs
---
Draft because it's based on #94. Please review that first.
--- 
Note that this isn't a performance change. It's about (hopefully) making
the library easier to use.
This is a corollary to https://github.com/georust/wkt/pull/89, but for
reading WKT, rather than writing. As we discussed there, probably there
is no reason for the user to care about the Wkt struct.
Note that the intermediate representation is still used (for now!), but
the user is no longer required to interact with it.
The road is open though for having a direct translation from Wkt text to
the geo-types (or whatever) represenation (see geozero for inspiration).
--- 
I also added the missing GeometryCollection::from(wkt) implementation to make this work for all geo-types.
> FromWkt trait for reading WKT without exposing the user to the intermediate representation.

- CHANGES.md
- Cargo.toml
- src/lib.rs
---
This is similar to what we do in geojson and elsewhere. Though I just learned about doc_auto_cfg which makes this way easier by automatically annotating any required items, rather than needing to try to sprinkle a bunch of calls all over like:
#[cfg_attr(docsrs, doc(cfg(feature = "geo-types")))]
mod my_geo_types_module;
e.g.
> Document all feature, and show feature requirements

- CHANGES.md
- Cargo.toml
---
Uses a SPDX license expression as recommended by [Cargo](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields).
This enables e.g. parsing via the [CycloneDX Rust Cargo Plugin](https://github.com/CycloneDX/cyclonedx-rust-cargo).
> Use SPDX license expression

- src/lib.rs
- src/types/coord.rs
- src/types/point.rs
> Support parse POINTZ, POINTM and POINTZM

- CHANGES.md
- src/deserialize/geo_types.rs
- src/deserialize/mod.rs
- src/geo_types_from_wkt.rs
- src/geo_types_to_wkt.rs
- src/lib.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
---
~~This is based on #109, so review that first.~~ Merged!
It's a large breaking change, so I'd appreciate getting at least a couple opinions.
> Simplify Wkt data structure

- CHANGES.md
- src/lib.rs
- src/types/coord.rs
- src/types/dimension.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/mod.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
> Fix parsing Z, M, and ZM WKT strings

- CHANGES.md
- Cargo.toml
---
I'll plan on releasing this tomorrow unless I hear otherwise.
> prepare for v0.11.0 release

- Cargo.toml
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
I included a write benchmark a while ago, but apparently never added it to Cargo.toml 😅
> include "write" bench in cargo.toml

- Cargo.toml
- src/lib.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
---
Ref https://github.com/georust/geo/pull/1157
> Implement geo-traits for reading from WKT

- benches/write.rs
- src/error.rs
- src/geo_traits_to_wkt.rs
- src/lib.rs
- src/to_wkt/geo_trait_impl.rs
- src/to_wkt/mod.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
---
This slightly changes the implementation for writing to WKT, partially based on @b4l's PR here https://github.com/geoarrow/geoarrow-rs/pull/788.
While porting the code to use traits, I realized that there was an _awful lot_ of string concatenation being performed. So for example, when writing a Polygon to WKT, **every single coordinate** would be allocated to a separate string, and then the coords of each **ring** would be concatenated and then **all rings** would be concatenated.
https://github.com/georust/wkt/blob/e1d838de2218f410422da28a23c26a7f6329505d/src/types/polygon.rs#L42-L52
This instead writes coordinates _directly_ to the output writer. So perhaps the performance differences in the discussion here https://github.com/georust/wkt/issues/118 were not primarily due to `ryu`. …
> Implement geo-traits for writing to WKT & perf improvement

- src/to_wkt/geo_trait_impl.rs
---
Ref https://github.com/georust/wkt/pull/124#discussion_r1859247848
> More inline impl trait

- src/geo_types_to_wkt.rs
- src/to_wkt/mod.rs
---
This avoids buffering when writing WKT to `std::io::Write`. It's considerably faster:
```
geo: write small wkt    time:   [570.44 ns 573.74 ns 578.31 ns]
change: [-30.487% -29.975% -29.481%] (p = 0.00 < 0.05)
Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
1 (1.00%) high mild
8 (8.00%) high severe
geo: write big wkt      time:   [2.0220 ms 2.0300 ms 2.0405 ms]
change: [-19.849% -19.214% -18.603%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
1 (1.00%) high mild
4 (4.00%) high severe
```
> Update `ToWkt::write_wkt` to not buffer string

- CHANGES.md
- Cargo.toml
- src/lib.rs
- src/to_wkt/geo_trait_impl.rs
- src/to_wkt/mod.rs
---
- Update top-level crate documentation with new information about geo-traits
- Add simple docstrings to all public functions
- Remove panic
> docs update & bump to 0.12

- src/geo_types_to_wkt.rs
> geo-types-0.7.16 has new winding order for Rect

- CHANGES.md
- src/geo_types_from_wkt.rs
- src/lib.rs
- src/types/coord.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
---
Similarly to `geo-types`, defaults to using `f64` as the `WktNum`. Not sure if this is controversial or not?
> Default to using `f64` for `WktNum` in WKT types

- CHANGES.md
- src/geo_types_to_wkt.rs
- src/to_wkt/mod.rs
---
Closes https://github.com/georust/wkt/issues/93.
There are three methods on the `ToWkt` trait. There's 
```rs
fn to_wkt(&self) -> Wkt<T>;
```
which will always allocate a `Wkt` struct.
This PR overrides the default implementation of
```rs
fn write_wkt(&self, writer: impl io::Write) -> io::Result<()> {
```
so that `write_wkt` does not construct a full `Wkt` struct before writing.
In theory we could also avoid the `Wkt` allocation for
```rs
fn wkt_string(&self) -> String {
```
by reusing the `write_wkt` method from inside of that, but there are a couple problems. 1) `wkt_string` is infallible, while `write_wkt` is fallible. 2) `write_wkt` requires a `std::io::Write`, which `&mut String` doesn't implement, so we'd have to write to a `Vec<u8>` and then parse that back to a `String`.
> Remove allocation to `Wkt` when writing geo-types via `write_wkt`

- CHANGES.md
- Cargo.toml
- src/deserialize/mod.rs
- src/geo_types_from_wkt.rs
- src/geo_types_to_wkt.rs
- src/infer_type.rs
- src/lib.rs
- src/types/coord.rs
- src/types/dimension.rs
- src/types/geometrycollection.rs
- src/types/linestring.rs
- src/types/multilinestring.rs
- src/types/multipoint.rs
- src/types/multipolygon.rs
- src/types/point.rs
- src/types/polygon.rs
---
Closes https://github.com/georust/wkt/issues/125
- Add `dim: Dimension` field to all WKT geometry types.
- Move the `.0` field to a named field in the struct, e.g. `coord` for `wkt::types::Point`. This is **breaking** because the `.0` field was public before.
- Add new constructors for each wkt type
- `new`: construct from a known inner and a dimension
- `from_*`, e.g. `Point::from_coord`, `LineString::from_coords`, `Polygon::from_rings`, which take the dimension from the first input item of the sequence and panic on empty sequences.
- `empty`: construct a new empty geometry from just a dimension
- Update tests. For anything that's now passed to `from_*`, I mostly changed all the `vec![]` to arrays for slightly simpler code.
- Fix `infer_type` to never return `None` for the dimension. …
> Store dimension in wkt types

- src/wkt_macro.rs
- [n/a] I added an entry to `CHANGES.md` if knowledge of this change could be valuable to users.
---
> DRY up WKT macros

- CHANGES.md
> Prepare release 0.14

- Cargo.toml
---
Follow up to #148 where I forgot to change the Cargo.toml package version 🤦‍♂️
> Set package version to 0.14
